 // Mega Menu Data Structure
// 10 Industries, each with 20 solutions (5x4 grid)

export type Solution = {
  title: string;
  description: string;
  href: string;
  icon?: string;
};

export type Industry = {
  id: string;
  name: string;
  description: string;
  solutions: Solution[];
};

export const INDUSTRIES: Industry[] = [
  {
    id: "fintech",
    name: "FinTech",
    description: "Financial services & banking platforms",
    solutions: [
      { title: "Quantitative Risk Labs", description: "Bespoke risk modeling & stress testing", href: "/services/quantitative-risk-labs" },
      { title: "Real-Time Liquidity Orchestration", description: "Dynamic liquidity routing & treasury orchestration", href: "/services/real-time-liquidity-orchestration" },
      { title: "Privacy-Preserving Analytics", description: "Federated & differential privacy analytics", href: "/services/privacy-preserving-analytics" },
      { title: "KYC Automation", description: "Identity verification", href: "/services/kyc-automation" },
      { title: "Fraud Detection", description: "AI-powered security", href: "/services/fraud-detection" },
      { title: "Lending Platforms", description: "Loan origination systems", href: "/services/lending-platforms" },
      { title: "Wealth Management", description: "Investment platforms", href: "/services/wealth-management" },
      { title: "Insurance Tech", description: "Policy & claims systems", href: "/services/insurance-tech" },
      { title: "Tokenized Assets Platform", description: "Issue and manage tokenized securities", href: "/services/tokenized-assets-platform" },
      { title: "RegTech Compliance", description: "Regulatory reporting", href: "/services/regtech-compliance" },
      { title: "Embedded Credit Underwriting", description: "Real-time credit decisions for embedded finance", href: "/services/embedded-credit-underwriting" },
      { title: "Neobank Core", description: "Digital-first banking", href: "/services/neobank-core" },
      { title: "Credit Scoring", description: "Alternative scoring", href: "/services/credit-scoring" },
      { title: "Synthetic Data Engine", description: "Privacy-safe synthetic datasets for finance", href: "/services/synthetic-data-engine" },
      { title: "POS Systems", description: "Point of sale", href: "/services/pos-systems" },
      { title: "Robo-Advisory", description: "Automated investing", href: "/services/robo-advisory" },
      { title: "Regulatory Automation Hub", description: "Automated filings & compliance workflows", href: "/services/regulatory-automation-hub" },
      { title: "Smart Contract Orchestration", description: "Orchestration for programmable agreements", href: "/services/smart-contract-orchestration" },
      { title: "Accounting Automation", description: "Financial reconciliation", href: "/services/accounting-automation" },
      { title: "Tax Compliance", description: "Automated tax filing", href: "/services/tax-compliance" },
    ],
  },
  {
    id: "healthcare",
    name: "HealthTech",
    description: "Medical & healthcare solutions",
    solutions: [
      { title: "Telemedicine", description: "Virtual consultations", href: "/services/telemedicine" },
      { title: "EHR Systems", description: "Electronic health records", href: "/services/ehr-systems" },
      { title: "Patient Portal", description: "Self-service access", href: "/services/patient-portal" },
      { title: "Medical Imaging", description: "DICOM & PACS", href: "/services/medical-imaging" },
      { title: "Lab Management", description: "Results & workflows", href: "/services/lab-management" },
      { title: "Pharmacy Systems", description: "Prescription management", href: "/services/pharmacy-systems" },
      { title: "Clinical Trials", description: "Research platforms", href: "/services/clinical-trials" },
      { title: "Health Analytics", description: "Population health", href: "/services/health-analytics" },
      { title: "Remote Monitoring", description: "IoT devices & wearables", href: "/services/remote-monitoring" },
      { title: "Appointment Booking", description: "Scheduling systems", href: "/services/appointment-booking" },
      { title: "Medical Billing", description: "Claims processing", href: "/services/medical-billing" },
      { title: "Drug Discovery", description: "AI-powered research", href: "/services/drug-discovery" },
      { title: "Mental Health Apps", description: "Digital therapy", href: "/services/mental-health-apps" },
      { title: "Care Coordination", description: "Provider networks", href: "/services/care-coordination" },
      { title: "Medical Devices", description: "Device integration", href: "/services/medical-devices" },
      { title: "Health Insurance", description: "Claims & benefits", href: "/services/health-insurance" },
      { title: "Genomics Platforms", description: "DNA sequencing", href: "/services/genomics-platforms" },
      { title: "Nutrition Tracking", description: "Diet & wellness", href: "/services/nutrition-tracking" },
      { title: "Hospital Management", description: "Operations systems", href: "/services/hospital-management" },
      { title: "Diagnostics AI", description: "Automated diagnosis", href: "/services/diagnostics-ai" },
    ],
  },
  {
    id: "ecommerce",
    name: "E-Commerce",
    description: "Retail & marketplace platforms",
    solutions: [
      { title: "Online Storefront", description: "Custom shops", href: "/services/online-storefront" },
      { title: "Marketplace Platform", description: "Multi-vendor systems", href: "/services/marketplace-platform" },
      { title: "Product Catalog", description: "Inventory management", href: "/services/product-catalog" },
      { title: "Shopping Cart", description: "Checkout optimization", href: "/services/shopping-cart" },
      { title: "Order Management", description: "Fulfillment systems", href: "/services/order-management" },
      { title: "Customer Reviews", description: "Rating & feedback", href: "/services/customer-reviews" },
      { title: "Recommendation Engine", description: "Personalization", href: "/services/recommendation-engine" },
      { title: "Loyalty Programs", description: "Rewards & points", href: "/services/loyalty-programs" },
      { title: "Dynamic Pricing", description: "Smart pricing", href: "/services/dynamic-pricing" },
      { title: "AR Try-On", description: "Virtual fitting", href: "/services/ar-try-on" },
      { title: "Subscription Box", description: "Recurring commerce", href: "/services/subscription-box" },
      { title: "Live Shopping", description: "Video commerce", href: "/services/live-shopping" },
      { title: "Social Commerce", description: "Shoppable posts", href: "/services/social-commerce" },
      { title: "Warehouse System", description: "Logistics automation", href: "/services/warehouse-system" },
      { title: "Returns Portal", description: "RMA management", href: "/services/returns-portal" },
      { title: "Gift Registry", description: "Wish lists", href: "/services/gift-registry" },
      { title: "B2B Portal", description: "Wholesale systems", href: "/services/b2b-portal" },
      { title: "Dropshipping", description: "Supplier integration", href: "/services/dropshipping" },
      { title: "POS Integration", description: "Omnichannel retail", href: "/services/pos-integration" },
      { title: "Search & Filters", description: "Product discovery", href: "/services/search-filters" },
    ],
  },
  {
    id: "edtech",
    name: "EdTech",
    description: "Education & learning platforms",
    solutions: [
      { title: "LMS Platform", description: "Learning management", href: "/services/lms-platform" },
      { title: "Virtual Classroom", description: "Live sessions", href: "/services/virtual-classroom" },
      { title: "Student Portal", description: "Academic access", href: "/services/student-portal" },
      { title: "Course Builder", description: "Content authoring", href: "/services/course-builder" },
      { title: "Assessment Tools", description: "Quizzes & exams", href: "/services/assessment-tools" },
      { title: "Gradebook", description: "Performance tracking", href: "/services/gradebook" },
      { title: "Video Lectures", description: "On-demand learning", href: "/services/video-lectures" },
      { title: "Interactive Labs", description: "Hands-on practice", href: "/services/interactive-labs" },
      { title: "Study Groups", description: "Peer collaboration", href: "/services/study-groups" },
      { title: "Certification", description: "Digital credentials", href: "/services/certification" },
      { title: "Tutoring Platform", description: "1-on-1 sessions", href: "/services/tutoring-platform" },
      { title: "Language Learning", description: "Adaptive lessons", href: "/services/language-learning" },
      { title: "School Admin", description: "SIS systems", href: "/services/school-admin" },
      { title: "Parent Portal", description: "Family engagement", href: "/services/parent-portal" },
      { title: "Attendance Tracking", description: "Automated records", href: "/services/attendance-tracking" },
      { title: "Library System", description: "Digital resources", href: "/services/library-system" },
      { title: "Career Services", description: "Job placement", href: "/services/career-services" },
      { title: "Alumni Network", description: "Community platform", href: "/services/alumni-network" },
      { title: "Admission Portal", description: "Application system", href: "/services/admission-portal" },
      { title: "Learning Analytics", description: "Student insights", href: "/services/learning-analytics" },
    ],
  },
  {
    id: "logistics",
    name: "Logistics",
    description: "Supply chain & transportation",
    solutions: [
      { title: "Fleet Management", description: "Vehicle tracking", href: "/services/fleet-management" },
      { title: "Route Optimization", description: "Smart routing", href: "/services/route-optimization" },
      { title: "Warehouse System", description: "Inventory control", href: "/services/warehouse-system-logistics" },
      { title: "Last Mile Delivery", description: "Final delivery", href: "/services/last-mile-delivery" },
      { title: "Freight Booking", description: "Carrier platform", href: "/services/freight-booking" },
      { title: "Customs Clearance", description: "Border automation", href: "/services/customs-clearance" },
      { title: "Track & Trace", description: "Shipment visibility", href: "/services/track-trace" },
      { title: "Cold Chain", description: "Temperature monitoring", href: "/services/cold-chain" },
      { title: "Dock Scheduling", description: "Yard management", href: "/services/dock-scheduling" },
      { title: "Returns Logistics", description: "Reverse supply chain", href: "/services/returns-logistics" },
      { title: "Driver App", description: "Mobile delivery", href: "/services/driver-app" },
      { title: "Load Planning", description: "Capacity optimization", href: "/services/load-planning" },
      { title: "Customs Broker", description: "Compliance docs", href: "/services/customs-broker" },
      { title: "Cross-Docking", description: "Direct transfer", href: "/services/cross-docking" },
      { title: "3PL Platform", description: "Third-party logistics", href: "/services/3pl-platform" },
      { title: "Carrier Portal", description: "Partner integration", href: "/services/carrier-portal" },
      { title: "Freight Audit", description: "Cost reconciliation", href: "/services/freight-audit" },
      { title: "Demand Forecasting", description: "Predictive planning", href: "/services/demand-forecasting" },
      { title: "Shipping Labels", description: "Label automation", href: "/services/shipping-labels" },
      { title: "Geo-Fencing", description: "Location alerts", href: "/services/geo-fencing" },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate",
    description: "Property & construction tech",
    solutions: [
      { title: "Property Listings", description: "MLS integration", href: "/services/property-listings" },
      { title: "Virtual Tours", description: "3D walkthroughs", href: "/services/virtual-tours" },
      { title: "CRM for Agents", description: "Lead management", href: "/services/crm-agents" },
      { title: "Booking System", description: "Viewing scheduler", href: "/services/booking-system-realestate" },
      { title: "Property Valuation", description: "AVM tools", href: "/services/property-valuation" },
      { title: "Mortgage Portal", description: "Loan applications", href: "/services/mortgage-portal" },
      { title: "Lease Management", description: "Tenant systems", href: "/services/lease-management" },
      { title: "Maintenance Requests", description: "Work orders", href: "/services/maintenance-requests" },
      { title: "HOA Portal", description: "Community management", href: "/services/hoa-portal" },
      { title: "Rent Collection", description: "Payment automation", href: "/services/rent-collection" },
      { title: "Smart Home IoT", description: "Building automation", href: "/services/smart-home-iot" },
      { title: "Construction PM", description: "Project tracking", href: "/services/construction-pm" },
      { title: "BIM Platform", description: "3D modeling", href: "/services/bim-platform" },
      { title: "Bidding System", description: "Contractor quotes", href: "/services/bidding-system" },
      { title: "Site Inspection", description: "Mobile audits", href: "/services/site-inspection" },
      { title: "Energy Management", description: "Utility tracking", href: "/services/energy-management" },
      { title: "Co-Working Booking", description: "Space reservations", href: "/services/coworking-booking" },
      { title: "Property Analytics", description: "Market insights", href: "/services/property-analytics" },
      { title: "Document Vault", description: "Secure storage", href: "/services/document-vault" },
      { title: "Title Search", description: "Deed verification", href: "/services/title-search" },
    ],
  },
  {
    id: "automotive",
    name: "Automotive",
    description: "Connected vehicles & mobility",
    solutions: [
      { title: "Fleet Telematics", description: "Vehicle data", href: "/services/fleet-telematics" },
      { title: "Ride Sharing", description: "Mobility platforms", href: "/services/ride-sharing" },
      { title: "Car Rental", description: "Booking systems", href: "/services/car-rental" },
      { title: "EV Charging", description: "Station network", href: "/services/ev-charging" },
      { title: "Auto Insurance", description: "Usage-based pricing", href: "/services/auto-insurance" },
      { title: "Parts Marketplace", description: "Aftermarket platform", href: "/services/parts-marketplace" },
      { title: "Service Booking", description: "Mechanic scheduler", href: "/services/service-booking" },
      { title: "Diagnostic Tools", description: "OBD-II systems", href: "/services/diagnostic-tools" },
      { title: "Connected Car", description: "Infotainment APIs", href: "/services/connected-car" },
      { title: "Parking Platform", description: "Space finder", href: "/services/parking-platform" },
      { title: "Dealer CRM", description: "Sales management", href: "/services/dealer-crm" },
      { title: "Test Drive Booking", description: "Showroom tools", href: "/services/test-drive-booking" },
      { title: "Trade-In Valuation", description: "Instant quotes", href: "/services/trade-in-valuation" },
      { title: "Auto Financing", description: "Loan calculators", href: "/services/auto-financing" },
      { title: "Roadside Assistance", description: "Emergency dispatch", href: "/services/roadside-assistance" },
      { title: "Vehicle Tracking", description: "GPS monitoring", href: "/services/vehicle-tracking" },
      { title: "Carpool Platform", description: "Shared commutes", href: "/services/carpool-platform" },
      { title: "Toll Payment", description: "Automated tolls", href: "/services/toll-payment" },
      { title: "Driver Safety", description: "Behavior analytics", href: "/services/driver-safety" },
      { title: "Auction Platform", description: "Wholesale marketplace", href: "/services/auction-platform" },
    ],
  },
  {
    id: "travel",
    name: "Travel & Hospitality",
    description: "Tourism & booking platforms",
    solutions: [
      { title: "Hotel Booking", description: "Reservations system", href: "/services/hotel-booking" },
      { title: "Flight Search", description: "GDS integration", href: "/services/flight-search" },
      { title: "Tour Packages", description: "Itinerary builder", href: "/services/tour-packages" },
      { title: "Activity Booking", description: "Experience platform", href: "/services/activity-booking" },
      { title: "Travel CRM", description: "Agent tools", href: "/services/travel-crm" },
      { title: "Loyalty Programs", description: "Rewards systems", href: "/services/loyalty-programs-travel" },
      { title: "Property Management", description: "Hotel operations", href: "/services/property-management" },
      { title: "Channel Manager", description: "OTA distribution", href: "/services/channel-manager" },
      { title: "Revenue Management", description: "Dynamic pricing", href: "/services/revenue-management" },
      { title: "Guest Portal", description: "Self-service", href: "/services/guest-portal" },
      { title: "Concierge App", description: "Guest services", href: "/services/concierge-app" },
      { title: "Restaurant POS", description: "F&B systems", href: "/services/restaurant-pos" },
      { title: "Event Management", description: "Venue booking", href: "/services/event-management" },
      { title: "Travel Insurance", description: "Policy management", href: "/services/travel-insurance" },
      { title: "Visa Services", description: "Document processing", href: "/services/visa-services" },
      { title: "Currency Exchange", description: "FX platform", href: "/services/currency-exchange" },
      { title: "Cruise Booking", description: "Sailing reservations", href: "/services/cruise-booking" },
      { title: "Car Hire", description: "Rental integration", href: "/services/car-hire" },
      { title: "Travel Guides", description: "Destination info", href: "/services/travel-guides" },
      { title: "Group Travel", description: "Corporate bookings", href: "/services/group-travel" },
    ],
  },
  {
    id: "media",
    name: "Media & Entertainment",
    description: "Content & streaming platforms",
    solutions: [
      { title: "Video Streaming", description: "OTT platforms", href: "/services/video-streaming" },
      { title: "Music Platform", description: "Audio streaming", href: "/services/music-platform" },
      { title: "Podcast Hosting", description: "Distribution systems", href: "/services/podcast-hosting" },
      { title: "Live Broadcasting", description: "Real-time streaming", href: "/services/live-broadcasting" },
      { title: "Content CMS", description: "Media management", href: "/services/content-cms" },
      { title: "Subscription Platform", description: "Paywall systems", href: "/services/subscription-platform" },
      { title: "Ad Server", description: "Monetization tools", href: "/services/ad-server" },
      { title: "Recommendation AI", description: "Content discovery", href: "/services/recommendation-ai" },
      { title: "Social Network", description: "Community platform", href: "/services/social-network" },
      { title: "Creator Tools", description: "Studio suite", href: "/services/creator-tools" },
      { title: "Ticketing System", description: "Event sales", href: "/services/ticketing-system" },
      { title: "Gaming Platform", description: "Multiplayer backend", href: "/services/gaming-platform" },
      { title: "NFT Marketplace", description: "Digital collectibles", href: "/services/nft-marketplace" },
      { title: "Photo Gallery", description: "Image hosting", href: "/services/photo-gallery" },
      { title: "News Portal", description: "Publishing CMS", href: "/services/news-portal" },
      { title: "Fan Engagement", description: "Community tools", href: "/services/fan-engagement" },
      { title: "Video Editor", description: "Cloud editing", href: "/services/video-editor" },
      { title: "Rights Management", description: "Licensing systems", href: "/services/rights-management" },
      { title: "Analytics Dashboard", description: "Audience insights", href: "/services/analytics-dashboard" },
      { title: "CDN Management", description: "Content delivery", href: "/services/cdn-management" },
    ],
  },
  {
    id: "saas",
    name: "SaaS & Enterprise",
    description: "Business software platforms",
    solutions: [
      { title: "CRM Platform", description: "Customer management", href: "/services/crm-platform" },
      { title: "Project Management", description: "Team collaboration", href: "/services/project-management" },
      { title: "HR Management", description: "People operations", href: "/services/hr-management" },
      { title: "Accounting Software", description: "Financial systems", href: "/services/accounting-software" },
      { title: "Help Desk", description: "Support ticketing", href: "/services/help-desk" },
      { title: "Email Marketing", description: "Campaign automation", href: "/services/email-marketing" },
      { title: "Analytics Platform", description: "Business intelligence", href: "/services/analytics-platform" },
      { title: "Document Management", description: "File collaboration", href: "/services/document-management" },
      { title: "Video Conferencing", description: "Virtual meetings", href: "/services/video-conferencing" },
      { title: "Time Tracking", description: "Productivity tools", href: "/services/time-tracking" },
      { title: "Inventory System", description: "Stock management", href: "/services/inventory-system" },
      { title: "Invoicing", description: "Billing automation", href: "/services/invoicing" },
      { title: "Workflow Automation", description: "Process optimization", href: "/services/workflow-automation" },
      { title: "Knowledge Base", description: "Documentation hub", href: "/services/knowledge-base" },
      { title: "Calendar Booking", description: "Scheduling system", href: "/services/calendar-booking" },
      { title: "Form Builder", description: "Data collection", href: "/services/form-builder" },
      { title: "Contract Management", description: "Legal workflow", href: "/services/contract-management" },
      { title: "Expense Tracking", description: "Spend management", href: "/services/expense-tracking" },
      { title: "Survey Platform", description: "Feedback tools", href: "/services/survey-platform" },
      { title: "API Gateway", description: "Integration hub", href: "/services/api-gateway" },
    ],
  },
];
